{% set name = "condeltri" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/condeltri-{{ version }}.tar.gz
  sha256: 96b2f75f88975479cee084cbdfabdd30421618e109fcc9576c8608288b680ba5

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - python
    - scikit-build-core
    - pybind11
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - condeltri
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mdealencar/PythonCDT
  summary: Constrained Delaunay Triangulation
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mdealencar
    - simutisernestas
